apiVersion: v1
kind: Service
metadata:
  name: mymdbmicro-service
  labels:
    name: mymdbmicro-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: mymdbmicro
  type: ClusterIP