apiVersion: apps/v1
kind: Deployment
metadata:
  name: mymdbmicro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mymdbmicro
  template:
    metadata:
      labels:
        app: mymdbmicro
    spec:
      containers:
      - name: mymdbmicro
        image: asimarunava/mymdbmicro
        livenessProbe:
          initialDelaySeconds: 30
          httpGet:
            path: /actuator/health
            port: 8080
        readinessProbe:
          initialDelaySeconds: 20
          httpGet:
            path: /hello/test
            port: 8080
        resources:
          requests:
            cpu: 0.5
            memory: 512Mi
          limits:
            cpu: 2.0
            memory: 1Gi
        ports:
        - name: http
          containerPort: 8080